version: '3.8'

services:
  training:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../data:/app/data
      - ../checkpoints:/app/checkpoints
      - ../logs:/app/logs
    command: python train.py

  inference:
    build:
      context: ..
      dockerfile: docker/Dockerfile.inference
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../checkpoints:/app/checkpoints
    ports:
      - "5000:5000"
    command: python inference.py 